# Namespaced config file
main:
    runFile: "config/runs_tests.csv" # "config/runs_tests.csv is the sample file that can be used for testing the pipeline setup"
    logPath: "logs"
    interimPath: "path/to/interim"
    resultPath: "path/to/final/results"

tools:
    guppy:
        guppyPath: "/usr/bin/guppy_basecaller"
        guppySimplex:
            cudaString: cuda:all
            chunksPerRunner: 512
        guppyDuplex:
            cudaString: cuda:all
            chunksPerRunner: 400
    dorado:
        doradoPath: "/path/to/dorado/dorado-0.5.3-linux-x64/bin/dorado"
        doradoSimplex:
            cudaString: cuda:all
        doradoDuplex:
            cudaString: cuda:all